### PR TITLE
Added support for CORS

### PR DESCRIPTION
**Pull request by harshit-budhraja**
Hi @sinedied,

Firstly, kudos on coming up with a wonderful API mocking tool. It really helps me with quicker development sprints in situations where integration testing would not immediately be possible for me.

So, I had a requirement where I wanted to mock an API which would be consumed by a front-end (both running on different origins) and hence I needed support for CORS. After doing so myself, I thought that it could be great if we could offer this out-of-the-box with `smoke` and hence this PR.

Please do get back to me with your thoughts on this.

### CODE REVIEW

**Comment by sinedied** [comment]
Look good to me, thanks for this PR! 👍 

Could you add some unit tests for it (in a separate PR, as I'll merge this one right away)?

**Comment by harshit-budhraja** [comment]
Definitely! I'll get back to you with another PR having some unit tests. Thanks a lot! 👍🏻

**Comment by sinedied** [comment]
Just published `3.1.0` with your changes, thanks again!

**Comment by harshit-budhraja** [comment]
Amazing! Thanks @sinedied 👌🏻
As far as tests are concerned, I've been occupied with work lately. Though, I've written a few of them but haven't really been able to spend sometime on the final refactoring. Will do it soon and send them across to you.

**Pull request merged**
